version: "3.9"
services:
  server1:
    build: ./node
    ports:
      - "8080:8080"
    environment:
      - SERVER_NAME=Servidor uno
    command: node node/index.js

  server2:
    build: ./python
    ports:
      - "4000:4000"
    environment:
      - SERVER_NAME=Servidor dos
    command: python3 python/main.py
