version: "3.9"
services:
  server1:
    build: ./node
    ports:
      - "8080:80"
    environment:
      - SERVER_NAME=Servidor uno

  server2:
    build: ./python
    ports:
      - "4000:80"
    environment:
      - SERVER_NAME=Servidor dos
